/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_BeadiestStar64_JNI_DynamicJNIDescription */

#ifndef _Included_com_github_BeadiestStar64_JNI_DynamicJNIDescription
#define _Included_com_github_BeadiestStar64_JNI_DynamicJNIDescription
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_BeadiestStar64_JNI_DynamicJNIDescription
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_BeadiestStar64_JNI_DynamicJNIDescription_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
